apiVersion: v1
kind: Namespace
metadata:
  name: storm-production
  labels:
    name: storm-production
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storm-resource-quota
  namespace: storm-production
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "10"
    services: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storm-limit-range
  namespace: storm-production
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container