apiVersion: v1
kind: ServiceAccount
metadata:
  name: storm-service-account
  namespace: storm-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storm-role
  namespace: storm-production
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storm-role-binding
  namespace: storm-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: storm-role
subjects:
- kind: ServiceAccount
  name: storm-service-account
  namespace: storm-production
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storm-app-pdb
  namespace: storm-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: storm
      component: app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storm-celery-pdb
  namespace: storm-production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: storm
      component: celery-worker